# Generated by Django 4.2.3 on 2023-07-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todohome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='datecomplete',
            field=models.CharField(max_length=30),
        ),
    ]
